[package]
name = "matui"
version = "0.1.0"
authors = ["Phil Kulak"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
crossterm = "0.25.0"
dirs = "4.0"
futures = "0.3.24"
log = "0.4"
once_cell = "1.17"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
simple-logging = "2.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread"] }
tui = "0.19.0"

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "1684dbe0a15fd089d89523378eea31575f19423c"
# version = "0.6"
features = [
    "markdown",
    "image-rayon",
]

